### ISSUE TITLE
Slight tweak needed for computation of FoV distribution metrics

### ISSUE THREAD

**Issue by tdwelly** [sdss/mugatu#5]
Hi Ilija,

thanks for pointing me to your DesignModeCheck.skies_fov() test: 
https://github.com/sdss/mugatu/blob/497b6b4e6645fa0139494cc330214444e51df400/python/mugatu/designmode.py#L765-L845

The specific case I was testing was a very marginal failure (metric=86.7 vs threshold=85.0), so I think I'll let it slide.

However, I have a suggestion to slightly modify the logic in the skies_fov() function, such that when the x_sci,y_sci are selected, the code also includes spectrophotometric standards (with the correct instrument type) within the sampled 'science' locations.

This would make the skies_fov() code more closely aligned with the tests described here:
https://wiki.sdss.org/display/OPS/Distribution+of+calibration+fibers+over+FoV
Specifically the statement: "In what follows when I refer to 'calibration fibers' and 'non-calibration fibers', I mean 'calibration fibers only of the currently type being considered'  and 'the rest of the fibers for that instrument' respectively"

Thanks

Tom

**Comment by imedan** [comment]
Hi Tom
This seems easy to implement. I have adapted the skies_fov(0 function to look like this:

    def skies_fov(self, instrument, return_metric=False):
        """
        Checks if design meets the FOV metric for the skies
        for some instrument. Returns True FOV metric met,
        False if not. Also, if no science targets in design
        returns True, while no skies returns False.

        Parameters
        ----------
        instrument: str
            Instrument to FOV metric.
            Must be 'BOSS' or 'APOGEE'.

        return_metric: boolean
            If True, will return the FOV metric
            for the design.

        Returns
        -------
        : boolean
            True FOV metric met,
            False if not. Also, if no science targets in design
            returns True, while no skies returns False.

        perc_dist: float
            Percentile distance between science assignments and
            skies (FOV metric) for the design. Only returned if
            return_metric=True.
        """
        # for now, return True (passing) if no FOV metric supplied
        if np.all(self.min_skies_fovmetric[instrument] == -999.):
            return True
        # get x,y of the skies
        x_sky = self.design['x'][(self.design['catalogID'] != -1) &
                                 (np.isin(self.design['carton_pk'],
                                          self.carton_classes['sky'])) &
                                 (self.design['obsWavelength'] == instrument)]
        y_sky = self.design['y'][(self.design['catalogID'] != -1) &
                                 (np.isin(self.design['carton_pk'],
                                          self.carton_classes['sky'])) &
                                 (self.design['obsWavelength'] == instrument)]

        x_sci = self.design['x'][(self.design['catalogID'] != -1) &
                                 ((np.isin(self.design['carton_pk'],
                                           self.carton_classes['science'])) |
                                 (np.isin(self.design['carton_pk'],
                                           self.carton_classes['std']))) &
                                 (self.design['obsWavelength'] == instrument)]
        y_sci = self.design['y'][(self.design['catalogID'] != -1) &
                                 ((np.isin(self.design['carton_pk'],
                                           self.carton_classes['science'])) |
                                 (np.isin(self.design['carton_pk'],
                                           self.carton_classes['std']))) &
                                 (self.design['obsWavelength'] == instrument)]

        # if no skies required, dont do check
        if self.n_skies_min[instrument] == 0:
            return True
        # if no skies, dont do check
        if len(x_sky) == 0:
            return False
        # if no science in band, doesnt matter?
        if len(x_sci) == 0:
            return True

        # create KDE tree
        tree = cKDTree(np.column_stack((x_sky, y_sky)))
        # get distances for nearest neighbors
        dd, ii = tree.query(np.column_stack((x_sci, y_sci)),
                            k=self.min_skies_fovmetric[instrument][0])
        # second column is the nth neighbor distance if k>1
        if self.min_skies_fovmetric[instrument][0] == 1:
            dists = dd
        else:
            dists = dd[:, 1]
        # this assumes percentile is on 0 to 100 scale
        perc_dist = np.percentile(dists,
                                  self.min_skies_fovmetric[instrument][1])
        if return_metric:
            if perc_dist < self.min_skies_fovmetric[instrument][2]:
                return True, perc_dist
            else:
                return False, perc_dist
        else:
            if perc_dist < self.min_skies_fovmetric[instrument][2]:
                return True
            else:
                return False

Also, to clarify your description of non-calibration' fibers here, does this mean that when doing to FOV metric for the standards, it makes sense to also include all instrument specific sky fibers into the 'non-cliabration' fibers?

**Comment by tdwelly** [comment]
Hi Ilija,
Looks good to me.  And yes, I would suggest to also modify the test for the standards in an equivalent way.

The reason being that we want to avoid having some complicated interplay between the FoV metric computed for for skies (standards) that also (indirectly) depends on the number+arrangement of standards (skies). 

One could even consider measuring the FoV metrics against _all_ other fibers of the given type (regardless of whether the robots carrying those fibers have been used to observe BOSS or APOGEE targets).

**Comment by imedan** [comment]
Thanks, that clarification makes sense. I will make that change to the metric calculation then.

> One could even consider measuring the FoV metrics against all other fibers of the given type (regardless of whether the robots carrying those fibers have been used to observe BOSS or APOGEE targets).

That is an interesting point as well... I think I will just do the first suggestion for now, but as I start validating more designs I will keep this in mind if it seems that the metric calculation is still too strict.
