### ISSUE TITLE
DesignMode checks emit warning even when there are no science fibers for one of BOSS, APOGEE

### ISSUE THREAD

**Issue by tdwelly** [sdss/mugatu#6]
I have noticed that the FPSDesign.validate_design() method emits instrument-specific calibration target warnings even when there are zero science fibers associated with that instrument.

E.g. in a BOSS-only design one might see the following warnings:
```
[WARNING]: Design does not meet minimum APOGEE skies for DesignMode (MugatuDesignModeWarning)
[WARNING]: Design does not meet FOV criteria for APOGEE skies for DesignMode (MugatuDesignModeWarning)
[WARNING]: Design does not meet minimum APOGEE standards for DesignMode (MugatuDesignModeWarning)
[WARNING]: Design does not meet FOV criteria for APOGEE standards for DesignMode (MugatuDesignModeWarning)
```
I would suggest to suppress (or downgrade) these warnings when nScienceFibers(APOGEE) = 0

I'm not sure if APOGEE-only designs are being considered, but if so then the equivalent suppression of BOSS warnings might also be desirable.

**Comment by imedan** [comment]
Yes, so I already do suppress these warnings when nScienceFibers = 0, I think what is happening is I always say it fails this metric if the number of skies or standards for for an instrument = 0. 

This obviously doesn't make sense for every design mode, as some design modes have the minimum number of skies/standards = 0. So, my proposal for this is I will additionally suppress these warnings if minSkies = 0 or minStandards = 0 for an instrument. Let me know how this sounds to you (and if it answers the issue you were having).

**Comment by tdwelly** [comment]
Hi,
Is it just related to the order in which the check is made?

i.e. the warning message is currently escaping because the check for **Nskies(inst), **Nstd(inst) etc comes before the test for whether **Nsci(inst) > 0?  

Flipping the order of the checks would suppress the warning.

Cheers
Tom

(**my parameter names, not intended to refer directly to mugatu code)

**Comment by imedan** [comment]
Ah, you are right that even with the new addition above, it probably does make sense to change the order as you specified. I have done this now and it seems to fix the issue when there are 0 science fibers for an instrument.
